
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
     java
    `java-library`
     application


    //publishing
    //`maven-publish`
}


dependencies {
    implementation("org.json:json:20220320")
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("com.squareup.okhttp3:okhttp:4.9.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.2.2")
    implementation("org.testng:testng:7.5")
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("org.slf4j:slf4j-simple:1.7.36")
}

group = "groupId"
version = "1.0-SNAPSHOT"
description = "Portfolio"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }

    withJavadocJar()
}

application {
    mainClass.set("com.lyit.csd.app.Main")
}
//tasks.test {
  //  useTestNG()
//}


tasks.getByName("run", JavaExec::class) {
    standardInput = System.`in`
}

tasks.named<Test>("test") {
    useTestNG()

    println("Executing tests...")

    testLogging.showStandardStreams = true
    testLogging.events("passed", "failed", "skipped")


}

sourceSets {
    main {
        java {

        }
    }

    test {
        java {

        }
    }
}

tasks.register<Javadoc>("generateCustomJavadocs") {
    println("Generating Javadocs...")
    source(sourceSets["main"].allJava)
}


/*publishing {
    publications {
        create<MavenPublication>("myLibrary") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            name = "myRepo"
            url = uri(layout.buildDirectory.dir("publications/myLibrary"))
        }
    }
}*/

allprojects {
    //tasks.withType<Test> {
        //maxParallelForks = 4
    //}

    tasks.withType<Javadoc> {
        println("in tasks.withType<Javadoc>")
        options.encoding = "UTF-8"
        isFailOnError = false
    }

    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
        }
    }
}


