
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `java-library`
    publishing
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.json:json:20220320")
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("com.squareup.okhttp3:okhttp:4.9.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.2.2")
    implementation("org.testng:testng:7.5")
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("org.slf4j:slf4j-simple:1.7.36")
}

group = "groupId"
version = "1.0-SNAPSHOT"
description = "Portfolio"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.named<Test>("test") {
    useTestNG()
}

tasks.register<Javadoc>("generateCustomJavadocs") {
    println("Generating Javadocs...")
    doLast{
        source("src/main")
        javadocTool
    }
}



publishing {
    publications {
        create<MavenPublication>("myLibrary") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            name = "myRepo"
            url = uri(layout.buildDirectory.dir("publications/myLibrary"))
        }
    }
}


