name: Gradle CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check our code
        uses: actions/checkout@v2
        
      # Make gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      # Run the build using gradle
      - name: Building with Gradle
        run: ./gradlew build
  
  #Publish javadocs to github
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 17
        java-package: jdk
    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        CLEAN: true
        FOLDER: build/docs/javadoc
        TARGET_FOLDER: javadoc
        
